### ISSUE TITLE
cant start Gateway

### ISSUE THREAD

**Issue by n3roGit** [mysensors/Raspberry#11]
i cant start the serial gateway.

- I have a Pi 1 B (first Generation with 256 MB RAM)
- capacitor connected to the NRF24L01+
- not overcloced PI
- CN connected to PIN 22 (GPIO 25)

i followed this tutorial:
http://forum.mysensors.org/topic/1151/tutorial-raspberry-pi-nrf24l01-direct-connection

When i start the programm in get this output:

./PiGatewaySerial
Starting PiGatewaySerial...
Protocol version - 1.4
Created PTY '/dev/pts/1'
Gateway tty: /dev/ttyMySensorsGateway
check wires

and a 100% CPU Load.

I cant end process with STRG+C. Only a KILL -9 stop it.

regards,
n3ro

**Comment by n3roGit** [comment]
i have found a wrong wire.... CSN.

Now it starts but i have still 100%CPU Load an no receive signal :-/

**Comment by rleoni** [comment]
Hello Guy's. I'm new here and I need some help.

I was trying to use MySensors on my Raspberry Pi 2, but I can't start the serial gateway.

Configurations:
No capacitor connected to the NRF24L01
not overclocked PI
CN not connected 

I followed this tutorial:
http://forum.mysensors.org/topic/1151/tutorial-raspberry-pi-nrf24l01-direct-connection

When I start the program in get this output:

./PiGatewaySerial
Starting PiGatewaySerial...
Protocol version - 1.4
Created PTY '/dev/pts/1'
Gateway tty: /dev/ttyMySensorsGateway

and my raspberry freezes. I can't finish the processes with STRG+C. What do I need to do?

regards,
Ricardo Leoni

**Comment by capitalfuse** [comment]
Could change Raspberry/librf24-bcm to https://github.com/TMRh20/RF24 for Rasbian Jessie.
Seems to work, but CPU usage is still 100%. Anybody has any hints to solve this issue?

pi@raspberrypi ~/Raspberry $ sudo ./PiGatewaySerial
Starting PiGatewaySerial...
Protocol version - 1.4
Created PTY '/dev/pts/1'
Gateway tty: /dev/ttyMySensorsGateway
================ SPI Configuration ================
CSN Pin  	 = CE0 (PI Hardware Driven)
CE Pin  	 = Custom GPIO25
Clock Speed	 = 8 Mhz
================ NRF Configuration ================
STATUS		 = 0x0e RX_DR=0 TX_DS=0 MAX_RT=0 RX_P_NO=7 TX_FULL=0
RX_ADDR_P0-1	 = 0xa8a8e1fc00 0xa8a8e1fc00
RX_ADDR_P2-5	 = 0xff 0xc4 0xc5 0xc6
TX_ADDR		 = 0x65646f4e32
RX_PW_P0-6	 = 0x20 0x20 0x20 0x00 0x00 0x00
EN_AA		 = 0x3b
EN_RXADDR	 = 0x06
RF_CH		 = 0x4c
RF_SETUP	 = 0x33
CONFIG		 = 0x0e
DYNPD/FEATURE	 = 0x3f 0x06
Data Rate	 = 250KBPS
Model		 = nRF24L01+
CRC Length	 = 16 bits
PA Power	 = PA_LOW

**Comment by henrikekblad** [comment]
See: 
http://forum.mysensors.org/topic/2437/step-by-step-procedure-to-connect-the-nrf24l01-to-the-gpio-pins-and-use-the-raspberry-as-a-serial-gateway
