### ISSUE TITLE
Raspberry is freezing after create the TTY

### ISSUE THREAD

**Issue by rleoni** [mysensors/Raspberry#13]
Hello Guy's. I'm new here and I need some help.

I was trying to use MySensors on my Raspberry Pi 2, but I can't start the serial gateway.

Configurations:
No capacitor connected to the NRF24L01
not overclocked PI
CN not connected

I followed this tutorial:
http://forum.mysensors.org/topic/1151/tutorial-raspberry-pi-nrf24l01-direct-connection

When I start the program in get this output:

./PiGatewaySerial
Starting PiGatewaySerial...
Protocol version - 1.4
Created PTY '/dev/pts/1'
Gateway tty: /dev/ttyMySensorsGateway

and my raspberry freezes. I can't finish the processes with STRG+C. What do I need to do?

regards,
Ricardo Leoni

**Comment by minscof** [comment]
You have to modify Makefile of librf24-bcm and to modify PiGatewaySerial.cpp because it is not compliant with RPI2.

You can look at issue #23

**Comment by henrikekblad** [comment]
Fixed
