### ISSUE TITLE
Update to MySensors v1.5

### ISSUE THREAD

**Issue by farconada** [mysensors/Raspberry#15]
Please update the lib to 1.5 version

**Comment by thozza** [comment]
The plan was and hopefully still is to merge the code base so there is no special repo for RPi variant.

**Comment by adamotte** [comment]
@thozza so if we use [Arduino code](https://github.com/mysensors/Arduino) it should work ?

**Comment by thozza** [comment]
@adamotte No I doubt it will work right now at least because there is no PiEEPROM.{c,h}. What I meant is that it does not make sense to rebase the mysensors/Raspberry to the 1.5 version, but rather add the support to the original Arduino library. There is some discussion going on right now, also about redesigning how library is structured. No outcomes yet.

**Comment by adamotte** [comment]
@thozza thx for the info can you give us a link of the discussion thread maybe.

**Comment by thozza** [comment]
@adamotte Unfortunately I'm not sure it is somewhere on the Internet. Better question for @henrikekblad

**Comment by adamotte** [comment]
By the way, i just build master branch on Pi 2 and PiGateway works with mysensors@1.5 on arduinos pro mini (at least for sensors already supported in 1.4)

**Comment by henrikekblad** [comment]
Yes, plan is to merge things. 

The discussion is currently just a hangout-session. Ping me on the mysensors forum in you want to join.  

We also started composing a google docs with some of the issues/ideas. You're free to add notes here also: 
https://docs.google.com/document/d/1NKq5uuNdnxF5jWnum7VT32mbKLjuvqlx2A5D1qQ-H3Q/edit?usp=sharing

**Comment by wergeld** [comment]
Any movement on this at this time?

**Comment by scobby** [comment]
any update on this? my serial gateway crashes often. hope a new Version can help

**Comment by henrikekblad** [comment]
This repo is deprecated, see:
https://www.mysensors.org/build/raspberry
