### ISSUE TITLE
Using GPIO_P1_22 instead of RPI_BPLUS_GPIO_J8_15 works perfectly fine on Raspi 2

### ISSUE THREAD

**Issue by GertSanders** [mysensors/Raspberry#17]
Following test in PiGatewaySerial.cpp should be reversed:

	/* create MySensors Gateway object */
#ifdef __PI_BPLUS
	gw = new MyGateway(RPI_BPLUS_GPIO_J8_15, RPI_BPLUS_GPIO_J8_24, BCM2835_SPI_SPEED_8MHZ, 1);
#else
	gw = new MyGateway(RPI_V2_GPIO_P1_22, BCM2835_SPI_CS0, BCM2835_SPI_SPEED_8MHZ, 1);
#endif

Using GPIO_P1_22 instead of RPI_BPLUS_GPIO_J8_15 works perfectly fine on Raspi 2

**Comment by henrikekblad** [comment]
Ok, will you create a pull request if this has been verified?

**Comment by GertSanders** [comment]
Hi Henrik, not sure how to do a pull request. In any case my RPI2 works great using pin 22.
