### ISSUE TITLE
make all in librf24-bcm crashes when installing in Jesse

### ISSUE THREAD

**Issue by sander76** [mysensors/Raspberry#20]
Having a clean rpi Jessie image.
When following the instructions and entering "make all" I get a lot of errors. failing the make.

Errors (a lot of them) look like this:

`bcm2835.c:1253:79: note: in expansion of macro ‘BCM2835_ST_BASE’ bcm2835_st = (volatile int32_t *)mapmem("st", BCM2835_BLOCK_SIZE, memfd, BCM2835_ST_BASE);`

**Comment by nivoc** [comment]
same here :-(

**Comment by agilljam** [comment]
I switched out the librf24-bcm to the latest version from http://tmrh20.github.io/ and got it compiling ok.
("Newly Optimized RF24 NRF24L01 Radio Library for Arduino")

**Comment by henrikekblad** [comment]
Fixed
