### ISSUE TITLE
Make it SystemD compatible.

### ISSUE THREAD

**Issue by ViperScull** [mysensors/Raspberry#21]
Could you create the SystemD .services equivalent to the init.d scripts (PiGateway and PiGatewaySerial) for those who use it?
thanks for all the work.

**Comment by cyberkov** [comment]
Hi! 
Writing systemd scripts is easy :-) i created in for the mqttgateway which you could use as a starting pointhttps://github.com/cyberkov/puppet-mysensors/blob/master/templates/mqttGateway2.service.erb 
Cheers Hannes
