### ISSUE TITLE
Compatibility with RPI2 ?

### ISSUE THREAD

**Issue by minscof** [mysensors/Raspberry#23]
I try to use this gateway with a rpi2
 cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 57.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2709
Revision        : a01041
Serial          : 000000002eec91d0

But I think the Makefile does not detect it is a RPI2 but a RPI B+, so 

 make
g++ -c -o PiGatewaySerial.o PiGatewaySerial.cpp -Wall -Ofast -mfpu=vfp -lpthread -g -D__Raspberry_Pi -mfloat-abi=hard -mtune=arm1176jzf-s -D_TTY_NAME=\"/dev/ttyMySensorsGateway\" -D_TTY_GROUPNAME=\"tty\" -march=armv7-a  -D__PI_BPLUS -I. -Ilibrf24-bcm/
g++ -o PiGatewaySerial MyGateway.o MySensor.o MyMessage.o PiEEPROM.o PiGatewaySerial.o -Wall -Ofast -mfpu=vfp -lpthread -g -D__Raspberry_Pi -mfloat-abi=hard -mtune=arm1176jzf-s -D_TTY_NAME=\"/dev/ttyMySensorsGateway\" -D_TTY_GROUPNAME=\"tty\" -march=armv7-a  -D__PI_BPLUS -I. -Ilibrf24-bcm/ -lrf24-bcm -lutil

So in the PiGatewaySerial.cpp the flag __PI_BPLUS  is set and the wrong parameter are taken.

I modify the code, but I still have problem with this gateaway on a rpi 2.

Can someone help me ?

**Comment by minscof** [comment]
I find the solution with this post http://forum.mysensors.org/topic/1151/tutorial-raspberry-pi-nrf24l01-direct-connection/44

I modified the Makefile in librf24-bcm to replace in line 37 
 CCFLAGS += -D BCM2835_PERI_BASE=0x${IOBASE}
by
CCFLAGS += -D BCM2835_PERI_BASE=0x3F000000

then  make; make install
and now everything is working for me on a rpi2

**Comment by jonathan-og** [comment]
Why isnt this patched by default?
