### ISSUE TITLE
ttyMySensorsGateway only accessable as root

### ISSUE THREAD

**Issue by sander76** [mysensors/Raspberry#25]
when I
```
ls -l ttyMySensorsGateway
```
I get
```
lrwxrwxrwx 1 root root 10 Jan  3 20:21 ttyMySensorsGateway -> /dev/pts/0
```
Meaning I can only access as root which results in all kinds of accessability issues. The makefile states
```
TTY_GROUPNAME := tty
```
But that doesn't seem to do anything. How to change ?

**Comment by dough29** [comment]
Try : ls -l /dev/pts/0

You'll see real owner.

**Comment by sander76** [comment]
It is the tty group. Which I would want for ttyMySensorsGateway too. The problem I have is when I want to read ttyMySensorsGateway from python for example: It has to run as root which sometimes is a problem. I can directly try to read pts/0 but that zero changes to another number at reboot... So I need to change my python script every time which I don't want. Or am I missing something? (No Linux expert here)

Sander.

**Comment by MartinHjelmare** [comment]
You can probably make a udev rule to either have the device show as the same name at every boot, or set group owner to something else.

**Comment by sander76** [comment]
Any tips on udev? Setting the group owner to something else will only work until I reboot.. Then it will be root again...

**Comment by sander76** [comment]
@dough29 
For my understanding. What does the 'real owner' mean ? Can I do something with it with respect to the issue I created?

**Comment by tazwurst** [comment]
Sorry, I have no idea what kind of problem you have?

You wrote your dev has the following rights: lrwxrwxrwx 1 root root
That means:
- owner has rwx
- group has rwx
- everyone has rwx

So everyone can read, write and execute. You cannt get more.

Mit freundlichen Grüßen / Kind regards

Andreas Maurer

Am 04.01.2016 um 07:59 schrieb sander76 <notifications@github.com<mailto:notifications@github.com>>:


@dough29<https://github.com/dough29>
For my understanding. What does the 'real owner' mean ? Can I do something with it with respect to the issue I created?

—
Reply to this email directly or view it on GitHub<https://github.com/mysensors/Raspberry/issues/25#issuecomment-168598398>.

________________________________

SoftService GmbH Training & Consulting - Am Gierath 20d - 40885 Ratingen - fon +49 2102 77086-0 - fax +49 2102 77086-27
Geschäftsführer / Managing Director Andreas Maurer - Registergericht Düsseldorf HRB 29778 - UStld / VAT DE-159759811

**Comment by dough29** [comment]
When I do "ls -l /dev/pts/0" I see owner = root and group = tty

So I added the user I want to use my gateway to the "tty" group and it's done.

**Comment by MartinHjelmare** [comment]
The udev rule will be run on every boot, setting group and/or name of the device. But you should try @dough29 solution first, that is easier. I described this process in the thread at mysensors forum.

**Comment by sander76** [comment]
I do ```ls -l /dev/pts/0``` and get

```crw-rw---- 1 root tty 136, 0 Jan  4 08:10 0```

I do ```sudo adduser pi tty``` to add the user pi to the tty group.

But opening the port in python using pyserial gives me a Permission denied error. (Also a ```cat /dev/ttyMySensorsGateway``` command gives me a permission denied..)

**Comment by sander76** [comment]
Thanks all... Seems to be working now !
