### ISSUE TITLE
error when sudo /etc/

### ISSUE THREAD

**Issue by J-Arji** [mysensors/Raspberry#34]
hi when that i run code : 

`sudo /etc/init.d/PiGatewaySerial start

`this error show:
`
[....] Starting PiGatewaySerial (via systemctl): PiGatewaySerial.serviceFailed to start PiGatewaySerial.service: Unit PiGatewaySerial.service failed to load: No such file or directory.`

**Comment by henrikekblad** [comment]
This repository is deprecated.

See:
https://www.mysensors.org/build/raspberry
